openapi: 3.0.1
info:
  contact:
    name: Toast developer support
  description: "A simple, single request, synchronous API to authorize credit card\
    \ \ntransactions associated with an orders API order.\n"
  title: Credit Cards API
  version: 1.0.0
servers:
- url: https://toast-api-server/ccpartner/v1
paths:
  /merchants/{merchantUuid}/payments/{paymentUuid}:
    put:
      description: |
        Authorize a credit card payment. Funds will be held until the
        payment is voided or captured.

        You must submit an orders API request to apply the payment to a
        check within five minutes of authorization, otherwise the
        payment is automatically voided.

        Payment must be captured within seven days of authorization,
        otherwise the payment is automatically voided. Capture
        occurs the evening after the order is fulfilled by the
        restaurant.
      operationId: merchantsMerchantUuidPaymentsPaymentUuidPut
      parameters:
      - description: |
          The Toast GUID of the merchant (restaurant) that will
          receive the payment. This is the same value as the
          Toast-Restaurant-External-ID.
        in: path
        name: merchantUuid
        required: true
        schema:
          type: string
      - description: |
          The unique identifier (UID) of this authorization,
          generated by the restaurant organization or integration
          partner.
        in: path
        name: paymentUuid
        required: true
        schema:
          type: string
      - description: |
          The GUID of the restaurant used as the context of the request.
        in: header
        name: Toast-Restaurant-External-ID
        required: true
        schema:
          type: string
      requestBody:
        content:
          '*/*':
            schema:
              $ref: "#/components/schemas/PaymentAuthorization"
        description: "The authorization request, including encrypted credit card information\
          \ and payment details."
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaymentStatus"
          description: The authorization request was processed. See the response for
            details.
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ToastError"
          description: The request was not valid. A required field may be missing.
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ToastError"
          description: The merchant (restaurant) does not exist.
        "409":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ToastError"
          description: |
            An authorization request was already made for this payment
            UUID. Verify that you are generating unique payment UUIDs
            for each request.  This can also occur if the same request
            is resubmitted, but the state has since been changed by
            another system (for example, voided on the POS).
        "422":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ToastError"
          description: |
            The request failed validation. The structure is not
            correct. A message with more information is returned if
            using the certification environment.
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ToastError"
          description: Unexpected error
      security:
      - oauth2:
        - credit_cards.authorization:write
      summary: Authorize a credit card
      x-codegen-request-body-name: paymentAuthorization
components:
  schemas:
    ToastError:
      description: Contains error details.
      example:
        description: description
        detail: detail
      properties:
        description:
          description: A human-readable description of the problem.
          type: string
        detail:
          description: "Error details, such as an exception and stack trace."
          type: string
      required:
      - description
      type: object
    PaymentStatus:
      description: Status of a payment.
      example:
        authorizationMetadata:
          last4: last4
          authorizationCode: authorizationCode
          localTransactionDate: 2000-01-23T04:56:07.000+00:00
          cardBrand: cardBrand
        amount: "{}"
        tipAmount: "{}"
        denialReason: denialReason
        paymentState: AUTHORIZED
        error: error
      properties:
        paymentState:
          description: |
            The state of the payment. Toast may add values to this field.
            Make sure that your implementation can handle additional
            values.
          enum:
          - AUTHORIZED
          - ACKNOWLEDGED
          - DENIED
          type: string
        authorizationMetadata:
          $ref: "#/components/schemas/AuthorizationMetadata"
        amount:
          description: "The amount of this payment, not including tip."
          properties: {}
          type: object
        tipAmount:
          description: The tip amount of this payment.
          properties: {}
          type: object
        denialReason:
          description: The reason a payment was denied. This must be displayed to
            the consumer.
          type: string
        error:
          description: "If the payment is in an error state, this will contain the\
            \ error."
          type: string
      required:
      - paymentState
      type: object
    AuthorizationMetadata:
      description: |
        Additional details about a payment, typically displayed on a receipt
        and logged by the partner.
      example:
        last4: last4
        authorizationCode: authorizationCode
        localTransactionDate: 2000-01-23T04:56:07.000+00:00
        cardBrand: cardBrand
      properties:
        localTransactionDate:
          description: |
            A copy of the `localTransactionDate` provided by the partner, in ISO 8601 format.
          format: date-time
          type: string
        cardBrand:
          description: "The brand of the credit card. For example, AMEX, Discover,\
            \ Visa, or Mastercard."
          type: string
        authorizationCode:
          description: |
            A code generated by card processing networks upon accepting an
            authorization request.
          type: string
        last4:
          description: |
            The final four digits of the credit card number.
          type: string
      required:
      - authorizationCode
      - cardBrand
      - last4
      - localTransactionDate
      type: object
    PartnerServiceInfo:
      description: |
        Information about the client that made the payment request. This
        information can be used for troubleshooting problems.
      example:
        instanceId: instanceId
        additionalInfo: additionalInfo
      properties:
        instanceId:
          description: |
            An identifier for the client that made the authorization
            request. For example, this might be a partner service
            instance ID that is visible in log messages.
          type: string
        additionalInfo:
          description: |
            Additional information about the service. For example, this
            might be a JSON structure containing the IP address and
            service version.
          type: string
      required:
      - instanceId
      type: object
    PaymentRequestMetadata:
      description: Metadata about the request being made.
      example:
        appVersion: appVersion
        partnerServiceInfo:
          instanceId: instanceId
          additionalInfo: additionalInfo
        deliveryAddress:
          country: country
          phone: phone
          address2: address2
          city: city
          address1: address1
          postalCode: postalCode
          name: name
          region: region
        appName: appName
        originIPAddr: originIPAddr
        localTransactionDate: 2000-01-23T04:56:07.000+00:00
        userAgent: userAgent
        billingAddress:
          country: country
          phone: phone
          address2: address2
          city: city
          address1: address1
          postalCode: postalCode
          name: name
          region: region
        cardFirst6: cardFirst6
        guestEmail: guestEmail
        cardLast4: cardLast4
        guestIdentifier: guestIdentifier
      properties:
        partnerServiceInfo:
          $ref: "#/components/schemas/PartnerServiceInfo"
        localTransactionDate:
          description: "The date and time, in ISO 8601 format, when the guest presents\
            \ their credit card. \n"
          format: date-time
          type: string
        originIPAddr:
          description: "The public ipv4 or ipv6 address of the cardholder making the\
            \ payment. The origin IP address is essential for detecting and preventing\
            \ fraud attempts in credit card authorization requests. To prevent disruption\
            \ to your transaction workflow, ensure the correct origin IP address is\
            \ used."
          type: string
        cardFirst6:
          description: |
            The first six digits of the credit card number. The first six
            digits are the bank identification number (BIN) for the card.
            Must exactly match that provided in the encrypted card data.
          type: string
        cardLast4:
          description: |
            The last four digits of the credit card number. Must exactly
            match that provided in the encrypted card data.
          type: string
        billingAddress:
          $ref: "#/components/schemas/BillingAddress"
        deliveryAddress:
          $ref: "#/components/schemas/DeliveryAddress"
        userAgent:
          description: |
            For payments taken through a browser, the browser's user agent string.
          type: string
        guestIdentifier:
          description: |
            An identifier for the guest making the payment such as
            an email address or phone number. Must consist of the following characters:
            `a-z, A-Z, 0-9, =, ., -, _, +, @, :, &, ^, %, !, $`
          type: string
        guestEmail:
          description: |
            The email address of the guest placing the payment.
          type: string
        appName:
          description: |
            A company-specific name for the mobile app (if any) the payment is made through.
            For instance, use 'MyCompany Android App' instead of 'Android App'
          type: string
        appVersion:
          description: |
            The version of the mobile app (if any) the payment is made through.
            You can use any string to represent the app version. There are no
            format or content requirements.
          type: string
      required:
      - billingAddress
      - cardFirst6
      - cardLast4
      - guestIdentifier
      - localTransactionDate
      - originIPAddr
      - partnerServiceInfo
      type: object
    PaymentAuthorization:
      description: A request to authorize a credit card payment.
      example:
        cardNumberOrigin: END_USER
        requestMetadata:
          appVersion: appVersion
          partnerServiceInfo:
            instanceId: instanceId
            additionalInfo: additionalInfo
          deliveryAddress:
            country: country
            phone: phone
            address2: address2
            city: city
            address1: address1
            postalCode: postalCode
            name: name
            region: region
          appName: appName
          originIPAddr: originIPAddr
          localTransactionDate: 2000-01-23T04:56:07.000+00:00
          userAgent: userAgent
          billingAddress:
            country: country
            phone: phone
            address2: address2
            city: city
            address1: address1
            postalCode: postalCode
            name: name
            region: region
          cardFirst6: cardFirst6
          guestEmail: guestEmail
          cardLast4: cardLast4
          guestIdentifier: guestIdentifier
        amount: 0.8008281904610115
        tipAmount: 6.027456183070403
        keyId: keyId
        willSaveCard: true
        encryptedCardData: "{}"
      properties:
        cardNumberOrigin:
          description: "The way that the credit card was provided for the payment\n\
            request. The value is `END_USER` if the cardholder entered\nthe card number\
            \ (PAN) as part of a web order. The value is\n`PARTNER_VAULT` if the PAN\
            \ was retrieved from a vault\ncontrolled by the integration partner.\n\
            \nThis value is used with `willSaveCard` to report information \nabout\
            \ stored credit card numbers to credit card provider \nnetworks. If your\
            \ organization is using stored credit card \ninformation for a credit\
            \ card authorization, this value must \nbe `PARTNER_VAULT`. The default\
            \ value is `END_USER`.\n"
          enum:
          - END_USER
          - PARTNER_VAULT
          type: string
        willSaveCard:
          description: "Indicates whether your organization will save the restaurant\
            \ \nguests' credit card information for future use.\n\nToast reports information\
            \ about stored credit card information \nto some credit card providers.\
            \ This \"card on file\" or \"stored \ncredentials\" reporting is required\
            \ by some credit card provider \nnetworks. These networks may impose fees\
            \ for non-compliance \nwith \"card on file\" reporting requirements.\n\
            \nNote that integration partners are responsible for any and \nall fees\
            \ incurred, and must comply with all applicable law \nand rules relevant\
            \ to, \"card on file\" consent, storage, use \nand reporting requirements\
            \ in accordance with card brand \nregulations and the integration partner\
            \ agreement.\n"
          type: boolean
        encryptedCardData:
          description: |
            A base64-encoded version of the encrypted card data payload.
            For information about encrypting and encoding credit card
            information, see the <cite>Toast API Developer's
            Guide</cite>.
          properties: {}
          type: object
        amount:
          description: |
            The check price that should be charged to the credit card,
            not including the tip. For example, the value `10.00`
            represents ten USD and zero cents. The `amount` must not be
            negative. The total of the `amount` value and the `tipAmount`
            value must be greater than zero.
          format: double
          type: number
        keyId:
          description: "The identifier of the encryption key and algorithm used \n\
            to encrypt the credit card data. Toast integration support \nprovides\
            \ this identifier along with the encryption key \nitself. If you received\
            \ an encryption key before June 2018,\nyou may omit this field. For all\
            \ API users, supplying a\nkeyId value prevents downtime during key rotations.\n"
          type: string
        tipAmount:
          description: |
            The tip that should be charged to the credit card. For
            example, the value `1.00` represents one USD and zero cents.
            The tip amount must not be negative. The total of the `amount`
            value and the `tipAmount` value must be greater than zero.
          format: double
          type: number
        requestMetadata:
          $ref: "#/components/schemas/PaymentRequestMetadata"
      required:
      - amount
      - cardNumberOrigin
      - encryptedCardData
      - keyId
      - requestMetadata
      - tipAmount
      - willSaveCard
      type: object
    BillingAddress:
      description: |
        An international billing address including name and phone number.
        A `BillingAddress` object for a `PaymentRequestMetadata` `billingAddress`
        value must exactly match address information you provide in encrypted
        credit card data.
      example:
        country: country
        phone: phone
        address2: address2
        city: city
        address1: address1
        postalCode: postalCode
        name: name
        region: region
      properties:
        name:
          description: |
            The name attached to the billing address. This is not necessarily
            the same as the name on the card.
          type: string
        phone:
          description: |
            The phone number associated with the account in [E.164 format](https://www.itu.int/rec/T-REC-E.164).
          type: string
        address1:
          description: Line 1 of the address
          type: string
        address2:
          description: Line 2 of the address
          type: string
        city:
          description: City of the address
          type: string
        region:
          description: Region or state of the address
          type: string
        postalCode:
          description: |
            Postal or ZIP code. If using a code with an extra four digits,
            for example a US ZIP+4 code, do not separate the extra digits.
            For example, `123451234`.
          type: string
        country:
          description: Country code using the ISO 3166-1 alpha-3 standard
          type: string
      required:
      - country
      - postalCode
      type: object
    DeliveryAddress:
      description: |
        A generic international delivery address including name and phone number.
      example:
        country: country
        phone: phone
        address2: address2
        city: city
        address1: address1
        postalCode: postalCode
        name: name
        region: region
      properties:
        name:
          description: |
            The name associated with the address.
          type: string
        phone:
          description: |
            The phone number associated with the account in [E.164 format](https://www.itu.int/rec/T-REC-E.164).
          type: string
        address1:
          description: Line 1 of the address
          type: string
        address2:
          description: Line 2 of the address
          type: string
        city:
          description: City of the address
          type: string
        region:
          description: Region or state of the address
          type: string
        postalCode:
          description: |
            Postal or ZIP code. If using a code with an extra four digits,
            for example a US ZIP+4 code, do not separate the extra digits.
            For example, `123451234`.
          type: string
        country:
          description: Country code using the ISO 3166-1 alpha-3 standard
          type: string
      required:
      - address1
      - city
      - country
      - postalCode
      - region
      type: object
  securitySchemes:
    oauth2:
      description: "Access to Toast APIs, specific endpoints, \nand specific API endpoint\
        \ operations is \ncontrolled by the scopes that are associated \nwith your\
        \ API account. \nA full reference for Toast API scopes and \ntheir capabilities\
        \ can be found in the\n[_Toast Developer Guide_](https://doc.toasttab.com/doc/devguide/apiScopes.html).\n"
      flows:
        clientCredentials:
          scopes:
            credit_cards.authorization:write: |
              Allows authorization of payments through the credit cards API.
          tokenUrl: https://toast-api-server/authentication/v1/authentication/login
      type: oauth2
x-original-swagger-version: "2.0"
